version: 2
jobs:
  deploy:
    working_directory: /tmp/build
    docker:
      - image: tegud/circleci-nodejs-serverless
    steps:
      - checkout

      - setup_remote_docker

      - run:
          command: |
            npm i
            serverless deploy
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy
